language: ruby
rvm:
  - 2.3.0
services:
  - redis-server
before_install:
  - cp config/database.yml.template config/database.yml
  - cp config/settings.yml.template config/settings.yml
script:
  - bundle exec rake db:setup
  - bundle exec rake
